JamesNK/Newtonsoft.Json.Schema

Src/Newtonsoft.Json.Schema/Infrastructure/JSchemaReader.cs

PR For issue #52

---

Src/Newtonsoft.Json.Schema/Infrastructure/JSchemaWriter.cs
Src/Newtonsoft.Json.Schema/Infrastructure/KnownSchemaCollection.cs

Fixed a performance issue of large JSchema objects serialization.

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0155Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/Validator.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/155

Fix validating multiple content

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0152Tests.cs
Src/Newtonsoft.Json.Schema/Generation/SchemaReferenceHandling.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/152

Fix JSchemaReferenceHandling flags

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0066Tests.cs
Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0162Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Discovery/JSchemaDiscovery.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Discovery/SchemaDiscovery.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/162

Provide additional info for invalid schema IDs

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0170Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/SchemaScope.cs

Fix validating property name with enum

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0166Tests.cs
Src/Newtonsoft.Json.Schema/Generation/JSchemaGeneratorInternal.cs
Src/Newtonsoft.Json.Schema/Generation/StringEnumGenerationProvider.cs
Src/Newtonsoft.Json.Schema/Infrastructure/EnumUtils.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/166

Fix using StringEnumGenerationProvider with enums containing duplicate values

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0187Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/JSchemaWriter.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/187

Fix dependencies not being written

---

Build/build.ps1
Doc/Introduction.aml
Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0195Tests.cs
Src/Newtonsoft.Json.Schema.Tests/Newtonsoft.Json.Schema.Tests.csproj
Src/Newtonsoft.Json.Schema.Tests/Resources/Schemas/Custom/Issue0195/A.json
Src/Newtonsoft.Json.Schema.Tests/Resources/Schemas/Custom/Issue0195/A2.json
Src/Newtonsoft.Json.Schema.Tests/Resources/Schemas/Custom/Issue0195/B.json
Src/Newtonsoft.Json.Schema.Tests/Resources/Schemas/Custom/Issue0195/C.json
Src/Newtonsoft.Json.Schema/Infrastructure/JSchemaReader.cs
Src/Newtonsoft.Json.Schema/Newtonsoft.Json.Schema.csproj

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/195

Remove portable target, fix nested root schema references

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0198Tests.cs
Src/Newtonsoft.Json.Schema.Tests/Resources/Schemas/Custom/Issue0198/sample.json
Src/Newtonsoft.Json.Schema.Tests/Resources/Schemas/Custom/Issue0198/types.json
Src/Newtonsoft.Json.Schema/Infrastructure/Discovery/SchemaDiscovery.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/198

Fix self referencing schema when schema id already has hash

---

Build/build.ps1
Src/Newtonsoft.Json.Schema.Tests/Infrastructure/JSchemaReaderTests.cs
Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0032Tests.cs
Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0200Tests.cs
Src/Newtonsoft.Json.Schema.Tests/JSchemaTests.cs
Src/Newtonsoft.Json.Schema.Tests/Newtonsoft.Json.Schema.Tests.csproj
Src/Newtonsoft.Json.Schema/Infrastructure/JSchemaWriter.cs
Src/Newtonsoft.Json.Schema/JSchema.cs
Src/global.json

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/200

Fix writing dependencies, add JSchema.ToString settings overload

---

README.md
Src/Newtonsoft.Json.Schema.Tests/JSchemaTests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/JSchemaWriter.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/207

Fix writing empty dependency collection

---

Src/Newtonsoft.Json.Schema.Tests/JSchemaGeneratorTests.cs
Src/Newtonsoft.Json.Schema.Tests/Newtonsoft.Json.Schema.Tests.csproj
Src/Newtonsoft.Json.Schema/Generation/JSchemaGeneratorInternal.cs
Src/Newtonsoft.Json.Schema/Infrastructure/ReflectionUtils.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/184

Fix generating schemas for ReadOnlyDictionary types

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0228Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/JSchemaConverter.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/228

Fix deserializing null with JSchemaConverter

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0238Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/Validator.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/238

Fix using JsonValidator with certain JTokenReader output

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0254Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/ConditionalScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/NotScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/SchemaScope.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/254

Fix validating schema not reference to itself

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0254Tests.cs
Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0258Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/AllOfScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/AnyOfScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/ConditionalScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/IfThenElseScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/NotScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/OneOfScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/RefScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/SchemaScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/Scope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/Validator.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/258

Fix circular dependencies between schemas

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0260Tests.cs
Src/Newtonsoft.Json.Schema.Tests/TestFixtureBase.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/SchemaScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/Validator.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/260

Fix if/then/else creating recursive child errors

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0264Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/DependentSchemaScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/ObjectScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/SchemaScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/Scope.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/264

Raise validation error for recursive dependentSchemas

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0262Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/SchemaVersionHelpers.cs
Src/Newtonsoft.Json.Schema/Newtonsoft.Json.Schema.csproj

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/262

Fix using ValidateVersion with draft 2019-09

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0268Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Discovery/SchemaDiscovery.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/268

Fix loading nested schemas in resolved schemas

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0162Tests.cs
Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0271Tests.cs
Src/Newtonsoft.Json.Schema.Tests/TestFixtureBase.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Discovery/JSchemaDiscovery.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Discovery/SchemaDiscovery.cs
Src/Newtonsoft.Json.Schema/Infrastructure/JSchemaReader.cs
Src/Newtonsoft.Json.Schema/Infrastructure/UriComparer.cs
Src/Newtonsoft.Json.Schema/JSchemaResolver.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/271
Also improve allocations.

Fix combining anchor with non-absolute ID

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0275Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/MathHelpers.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/275

Fix divide by zero error with small multipleOf

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0316Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/DateTimeParser.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/PrimativeScope.cs

Fix date-time and time with many fractional seconds

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0331Tests.cs
Src/Newtonsoft.Json.Schema/Generation/JSchemaGeneratorInternal.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/331

Fix schema generation of sealed type with extension data

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0339Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Discovery/JSchemaDiscovery.cs
Src/Newtonsoft.Json.Schema/Infrastructure/JSchemaReader.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/339

Fix errors from dynamic scope when validation schema load

---

Src/Newtonsoft.Json.Schema.Tests/Issues/Issue0357Tests.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/ConditionalScope.cs
Src/Newtonsoft.Json.Schema/Infrastructure/Validation/Scope.cs

Fixes https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/357

Fix raising validation errors with circular reference in child errors
